import { defineObject, FieldType } from 'twenty-sdk/define';

import { EVENT_MODALITY } from 'src/constants/domain-options';
import {
  EVENT_AUDIENCE_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_ASSEMBLY_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_CITY_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_CONFIRMED_AUDIENCE_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_END_AT_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_EXECUTION_NOTES_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_EXECUTION_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_FEEDBACK_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_FEEDBACK_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_LOCATION_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_MENU_SUMMARY_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_MODALITY_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_OBJECT_UNIVERSAL_IDENTIFIER,
  EVENT_RESTRICTIONS_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_ROOMS_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_SERVICE_FORMAT_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_START_AT_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_SUPPLY_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_TEAM_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_TRAVEL_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  EVENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export default defineObject({
  universalIdentifier: EVENT_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'corporateEvent',
  namePlural: 'corporateEvents',
  labelSingular: 'Evento',
  labelPlural: 'Eventos',
  description: 'Dados operacionais do evento vendido pela GSH.',
  icon: 'IconCalendarEvent',
  labelIdentifierFieldMetadataUniversalIdentifier:
    EVENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: EVENT_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Nome do evento',
      icon: 'IconCalendarEvent',
    },
    {
      universalIdentifier: EVENT_MODALITY_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'modality',
      label: 'Modalidade',
      icon: 'IconMapPin',
      isNullable: true,
      options: [
        { id: 'c70f992d-7406-44a4-b016-77ab12d2cf8a', value: EVENT_MODALITY.INTERNAL, label: 'Interno / na casa', position: 0, color: 'blue' },
        { id: '0933c54e-9419-4788-a7c7-a0ef1aff8bd3', value: EVENT_MODALITY.EXTERNAL, label: 'Externo / fora da casa', position: 1, color: 'orange' },
      ],
    },
    {
      universalIdentifier: EVENT_TYPE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'eventType',
      label: 'Tipo do evento',
      icon: 'IconCategory',
      isNullable: true,
      options: [
        { id: '333f82ce-09b9-4dd9-9ad7-d391b6cf7f8b', value: 'COFFEE_BREAK', label: 'Coffee break', position: 0, color: 'blue' },
        { id: '7e9dca79-763f-47e1-ad35-ba4dc4234e39', value: 'WELCOME_COFFEE', label: 'Welcome coffee', position: 1, color: 'cyan' },
        { id: '81de323e-4d95-4760-bab9-47a534c624d2', value: 'HAPPY_HOUR', label: 'Happy hour', position: 2, color: 'purple' },
        { id: 'ac841f03-a7a6-4944-baec-d9b7a119253a', value: 'COCKTAIL', label: 'Coquetel', position: 3, color: 'pink' },
        { id: '16467068-0e39-4c17-86ba-d143c08e5fab', value: 'FAIR', label: 'Feira', position: 4, color: 'orange' },
        { id: 'dd78c39c-dd15-4a21-bddf-175a5d185f32', value: 'MEAL', label: 'Refeição', position: 5, color: 'green' },
        { id: '8959c891-bcad-4be2-87f2-5f9ed77d34e1', value: 'OTHER', label: 'Outro', position: 6, color: 'gray' },
      ],
    },
    { universalIdentifier: EVENT_START_AT_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.DATE_TIME, name: 'startAt', label: 'Início', icon: 'IconCalendarTime', isNullable: true },
    { universalIdentifier: EVENT_END_AT_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.DATE_TIME, name: 'endAt', label: 'Fim', icon: 'IconCalendarTime', isNullable: true },
    { universalIdentifier: EVENT_LOCATION_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'location', label: 'Local', icon: 'IconMapPin', isNullable: true },
    { universalIdentifier: EVENT_CITY_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'city', label: 'Cidade', icon: 'IconBuilding', isNullable: true },
    { universalIdentifier: EVENT_AUDIENCE_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.NUMBER, name: 'estimatedAudience', label: 'Público estimado', icon: 'IconUsers', isNullable: true },
    { universalIdentifier: EVENT_CONFIRMED_AUDIENCE_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.NUMBER, name: 'confirmedAudience', label: 'Público confirmado', icon: 'IconUserCheck', isNullable: true },
    { universalIdentifier: EVENT_SERVICE_FORMAT_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'serviceFormat', label: 'Formato de serviço', icon: 'IconToolsKitchen2', isNullable: true },
    { universalIdentifier: EVENT_ROOMS_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.TEXT, name: 'rooms', label: 'Salas e espaços', icon: 'IconBuildingCommunity', isNullable: true },
    { universalIdentifier: EVENT_MENU_SUMMARY_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.RICH_TEXT, name: 'menuSummary', label: 'Resumo do cardápio', icon: 'IconToolsKitchen2', isNullable: true },
    { universalIdentifier: EVENT_RESTRICTIONS_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.RICH_TEXT, name: 'restrictions', label: 'Restrições e observações', icon: 'IconAlertTriangle', isNullable: true },
    {
      universalIdentifier: EVENT_ASSEMBLY_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'assemblyStatus',
      label: 'Montagem',
      icon: 'IconBuildingWarehouse',
      isNullable: true,
      options: [
        { id: 'ec124830-0071-4a58-877c-c33f196bcc58', value: 'NOT_APPLICABLE', label: 'Não aplicável', position: 0, color: 'gray' },
        { id: '745cc957-d34f-4524-8b4a-031945470dbc', value: 'PENDING', label: 'Pendente', position: 1, color: 'orange' },
        { id: '1eb1e21c-ea78-46a0-b9db-1d8de03ec25e', value: 'READY', label: 'Pronta', position: 2, color: 'green' },
      ],
    },
    {
      universalIdentifier: EVENT_TRAVEL_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'travelStatus',
      label: 'Deslocamento',
      icon: 'IconTruckDelivery',
      isNullable: true,
      options: [
        { id: '8c9b4f34-0092-4497-9783-e267735c333a', value: 'NOT_APPLICABLE', label: 'Não aplicável', position: 0, color: 'gray' },
        { id: 'c77027e2-524d-4f6c-906b-1f14c12a22e9', value: 'PENDING', label: 'Pendente', position: 1, color: 'orange' },
        { id: '2eee0e30-ab9e-4c9f-a299-6c344ad21586', value: 'READY', label: 'Pronto', position: 2, color: 'green' },
      ],
    },
    {
      universalIdentifier: EVENT_SUPPLY_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'supplyStatus',
      label: 'Abastecimento',
      icon: 'IconPackage',
      isNullable: true,
      options: [
        { id: '3091bc1c-c74c-4047-a310-e4b27ad0d545', value: 'NOT_APPLICABLE', label: 'Não aplicável', position: 0, color: 'gray' },
        { id: 'bea5b99e-274f-4749-9b14-8e312fbac285', value: 'PENDING', label: 'Pendente', position: 1, color: 'orange' },
        { id: '4d56a1dc-0338-4626-9ad5-d4b8146d8c56', value: 'READY', label: 'Pronto', position: 2, color: 'green' },
      ],
    },
    {
      universalIdentifier: EVENT_TEAM_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'teamStatus',
      label: 'Equipe',
      icon: 'IconUsers',
      isNullable: true,
      options: [
        { id: 'cd1bbb5b-df42-497a-891d-16afb96c07f3', value: 'NOT_APPLICABLE', label: 'Não aplicável', position: 0, color: 'gray' },
        { id: '657fbec2-2038-4d60-b79e-8c3c2f4cf2c0', value: 'PENDING', label: 'Pendente', position: 1, color: 'orange' },
        { id: '9a0bd3b1-75e6-464b-ac20-96c6c87a3e40', value: 'READY', label: 'Pronta', position: 2, color: 'green' },
      ],
    },
    {
      universalIdentifier: EVENT_EXECUTION_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'executionStatus',
      label: 'Status da execução',
      icon: 'IconProgress',
      isNullable: true,
      options: [
        { id: 'bf16d567-6c87-4cef-bc2c-e042e89f05ad', value: 'NOT_STARTED', label: 'Não iniciada', position: 0, color: 'gray' },
        { id: '05e50e1b-544c-45dc-8120-d0bfea3b440e', value: 'SCHEDULED', label: 'Agendada', position: 1, color: 'blue' },
        { id: 'c3356896-730b-4afb-aad2-186df80a7041', value: 'IN_PROGRESS', label: 'Em execução', position: 2, color: 'orange' },
        { id: '006cdebf-41be-4d02-80a0-6dbeb46ff712', value: 'COMPLETED', label: 'Concluída', position: 3, color: 'green' },
      ],
    },
    { universalIdentifier: EVENT_EXECUTION_NOTES_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.RICH_TEXT, name: 'executionNotes', label: 'Notas da execução', icon: 'IconNotes', isNullable: true },
    {
      universalIdentifier: EVENT_FEEDBACK_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'feedbackStatus',
      label: 'Status do feedback',
      icon: 'IconMessageCircle',
      isNullable: true,
      options: [
        { id: 'b9d9ff58-b718-4405-8a0d-ac9a0f5942f4', value: 'PENDING', label: 'Pendente', position: 0, color: 'orange' },
        { id: '5d25eb19-f678-411f-a995-d4f2f1d1b2fc', value: 'REQUESTED', label: 'Solicitado', position: 1, color: 'blue' },
        { id: '5678683f-32dc-48c7-9684-69a539bff8e3', value: 'RECEIVED', label: 'Recebido', position: 2, color: 'green' },
        { id: 'bb7a7dd6-1288-464c-9d4c-338c611bd439', value: 'NOT_APPLICABLE', label: 'Não aplicável', position: 3, color: 'gray' },
      ],
    },
    { universalIdentifier: EVENT_FEEDBACK_FIELD_UNIVERSAL_IDENTIFIER, type: FieldType.RICH_TEXT, name: 'feedback', label: 'Feedback do cliente', icon: 'IconMessageCircle', isNullable: true },
  ],
});
